# Generated by Django 5.2 on 2025-04-07 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phrase_orig', models.TextField()),
                ('phrase_translation', models.TextField()),
            ],
            options={
                'db_table': 'glossary',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('difficulty', models.TextField()),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'leaderboard',
            },
        ),
    ]
