# Generated by Django 5.2 on 2025-04-10 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('phrase_english', models.TextField()),
                ('phrase_japanese', models.TextField()),
                ('phrase_kana', models.TextField()),
                ('phrase_chinese', models.TextField()),
                ('phrase_pinyin', models.TextField()),
            ],
            options={
                'db_table': 'glossary',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.TextField()),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard',
            },
        ),
    ]
